# Generated by Django 5.2.5 on 2025-09-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_bio_user_created_at_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
